services:
  database:
    image: postgres:15
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  server:
    env_file: .env
    build: .
    depends_on:
      - database
    ports:
      - "4000:5432"
